module_list = {
	'QtCore',
	'QtDesigner',
	'QtGui',
	'QtNetwork',
	'QtOpenGL',
	'QtSql',
	'QtXml',
	'Qt3Support',
}

files_set = {
	["QtCore/Qt"] = 1,
	["QtCore/QTS"] = 1,
	["QtCore/QDir"] = 1,
	["QtCore/QMap"] = 1,
	["QtCore/QSet"] = 1,
	["QtCore/QUrl"] = 1,
	["QtCore/QPointF"] = 1,
	["QtCore/QSharedDataPointer"] = 1,
	["QtCore/QStringMatcher"] = 1,
	["QtCore/QVariantMap"] = 1,
	["QtCore/QRegExp"] = 1,
	["QtCore/QVectorData"] = 1,
	["QtCore/QIODevice"] = 1,
	["QtCore/QReadLocker"] = 1,
	["QtCore/QVariantComparisonHelper"] = 1,
	["QtCore/QThread"] = 1,
	["QtCore/QString"] = 1,
	["QtCore/QLatin1String"] = 1,
	["QtCore/QVector"] = 1,
	["QtCore/QtPluginInstanceFunction"] = 1,
	["QtCore/QBool"] = 1,
	["QtCore/QChar"] = 1,
	["QtCore/QDate"] = 1,
	["QtCore/QFile"] = 1,
	["QtCore/QFlag"] = 1,
	["QtCore/QHash"] = 1,
	["QtCore/QLine"] = 1,
	["QtCore/QList"] = 1,
	["QtCore/QPair"] = 1,
	["QtCore/QRect"] = 1,
	["QtCore/QSize"] = 1,
	["QtCore/QTime"] = 1,
	["QtCore/QUuid"] = 1,
	["QtCore/Q_PID"] = 1,
	["QtCore/QPointer"] = 1,
	["QtCore/QAbstractEventDispatcher"] = 1,
	["QtCore/QCharRef"] = 1,
	["QtCore/QStringListIterator"] = 1,
	["QtCore/QAbstractListModel"] = 1,
	["QtCore/QChildEvent"] = 1,
	["QtCore/QMutableSetIterator"] = 1,
	["QtCore/QFactoryInterface"] = 1,
	["QtCore/QGlobalStatic"] = 1,
	["QtCore/Q_INT16"] = 1,
	["QtCore/Q_INT32"] = 1,
	["QtCore/Q_INT64"] = 1,
	["QtCore/Q_LLONG"] = 1,
	["QtCore/QCache"] = 1,
	["QtCore/QDebug"] = 1,
	["QtCore/QEvent"] = 1,
	["QtCore/QFlags"] = 1,
	["QtCore/Q_UINT8"] = 1,
	["QtCore/Q_ULONG"] = 1,
	["QtCore/QMutableStringListIterator"] = 1,
	["QtCore/QLineF"] = 1,
	["QtCore/QMutex"] = 1,
	["QtCore/QProcess"] = 1,
	["QtCore/QPoint"] = 1,
	["QtCore/QRectF"] = 1,
	["QtCore/QQueue"] = 1,
	["QtCore/QSizeF"] = 1,
	["QtCore/QStack"] = 1,
	["QtCore/QTimer"] = 1,
	["QtCore/QTextCodecFactoryInterface"] = 1,
	["QtCore/Q_INT8"] = 1,
	["QtCore/Q_LONG"] = 1,
	["QtCore/QBasicAtomicPointer"] = 1,
	["QtCore/QTextCodecPlugin"] = 1,
	["QtCore/QtCore"] = 1,
	["QtCore/QByteRef"] = 1,
	["QtCore/QBitArray"] = 1,
	["QtCore/QVariantList"] = 1,
	["QtCore/QListData"] = 1,
	["QtCore/QMetaEnum"] = 1,
	["QtCore/QMetaType"] = 1,
	["QtCore/QModelIndexList"] = 1,
	["QtCore/QSocketNotifier"] = 1,
	["QtCore/QDateTime"] = 1,
	["QtCore/QDataStream"] = 1,
	["QtCore/QStringList"] = 1,
	["QtCore/QObjectData"] = 1,
	["QtCore/QObjectList"] = 1,
	["QtCore/QForeachContainer"] = 1,
	["QtCore/QtAlgorithms"] = 1,
	["QtCore/QLibraryInfo"] = 1,
	["QtCore/QSharedData"] = 1,
	["QtCore/QByteArrayMatcher"] = 1,
	["QtCore/QMutableVectorIterator"] = 1,
	["QtCore/QTypeInfo"] = 1,
	["QtCore/QVectorTypedData"] = 1,
	["QtCore/QSemaphore"] = 1,
	["QtCore/QThreadStorage"] = 1,
	["QtCore/QMetaProperty"] = 1,
	["QtCore/QVectorIterator"] = 1,
	["QtCore/QPersistentModelIndex"] = 1,
	["QtCore/QtDebug"] = 1,
	["QtCore/QMutexLocker"] = 1,
	["QtCore/QLibrary"] = 1,
	["QtCore/QSignalMapper"] = 1,
	["QtCore/QTextDecoder"] = 1,
	["QtCore/QMetaClassInfo"] = 1,
	["QtCore/QSetIterator"] = 1,
	["QtCore/QtMsgHandler"] = 1,
	["QtCore/QMapData"] = 1,
	["QtCore/QHashIterator"] = 1,
	["QtCore/QMultiMap"] = 1,
	["QtCore/QFileEngineHandler"] = 1,
	["QtCore/QHashDummyValue"] = 1,
	["QtCore/QBasicTimer"] = 1,
	["QtCore/QCoreApplication"] = 1,
	["QtCore/QFileInfo"] = 1,
	["QtCore/QTimerEvent"] = 1,
	["QtCore/QNoImplicitBoolCast"] = 1,
	["QtCore/QMutableHashIterator"] = 1,
	["QtCore/QMutableMapIterator"] = 1,
	["QtCore/QEventLoop"] = 1,
	["QtCore/QCustomEvent"] = 1,
	["QtCore/QForeachContainerBase"] = 1,
	["QtCore/QMultiHash"] = 1,
	["QtCore/QGenericReturnArgument"] = 1,
	["QtCore/QHashData"] = 1,
	["QtCore/QHashNode"] = 1,
	["QtCore/QSysInfo"] = 1,
	["QtCore/QFileInfoListIterator"] = 1,
	["QtCore/QByteArray"] = 1,
	["QtCore/QModelIndex"] = 1,
	["QtCore/QWaitCondition"] = 1,
	["QtCore/QVarLengthArray"] = 1,
	["QtCore/QMetaMethod"] = 1,
	["QtCore/QTextEncoder"] = 1,
	["QtCore/QLatin1Char"] = 1,
	["QtCore/QMimeData"] = 1,
	["QtCore/QMetaObject"] = 1,
	["QtCore/QThreadStorageData"] = 1,
	["QtCore/QTemporaryFile"] = 1,
	["QtCore/QTextCodec"] = 1,
	["QtCore/QListIterator"] = 1,
	["QtCore/QLinkedListData"] = 1,
	["QtCore/QFileInfoList"] = 1,
	["QtCore/QLinkedListNode"] = 1,
	["QtCore/QNoDebug"] = 1,
	["QtCore/QReadWriteLock"] = 1,
	["QtCore/QTextStream"] = 1,
	["QtCore/QObjectCleanupHandler"] = 1,
	["QtCore/QtCleanUpFunction"] = 1,
	["QtCore/QAtomic"] = 1,
	["QtCore/QBitRef"] = 1,
	["QtCore/QTextStreamFunction"] = 1,
	["QtCore/QGenericArgument"] = 1,
	["QtCore/QObjectUserData"] = 1,
	["QtCore/QVariant"] = 1,
	["QtCore/QBuffer"] = 1,
	["QtCore/QLinkedList"] = 1,
	["QtCore/QArgument"] = 1,
	["QtCore/QMetaTypeId"] = 1,
	["QtCore/QtGlobal"] = 1,
	["QtCore/QTextOStream"] = 1,
	["QtCore/QMutableListIterator"] = 1,
	["QtCore/QFileEngine"] = 1,
	["QtCore/QWriteLocker"] = 1,
	["QtCore/QBasicAtomic"] = 1,
	["QtCore/QTextStreamManipulator"] = 1,
	["QtCore/QStdWString"] = 1,
	["QtCore/QLinkedListIterator"] = 1,
	["QtCore/Q_UINT16"] = 1,
	["QtCore/Q_UINT32"] = 1,
	["QtCore/Q_UINT64"] = 1,
	["QtCore/Q_ULLONG"] = 1,
	["QtCore/QAbstractTableModel"] = 1,
	["QtCore/QMapIterator"] = 1,
	["QtCore/QAtomicPointer"] = 1,
	["QtCore/QLocale"] = 1,
	["QtCore/QMutableLinkedListIterator"] = 1,
	["QtCore/QConstString"] = 1,
	["QtCore/QAbstractItemModel"] = 1,
	["QtCore/QSettings"] = 1,
	["QtCore/QObject"] = 1,
	["QtCore/QTextIStream"] = 1,
	["QtCore/QReturnArgument"] = 1,
	["QtCore/QTranslator"] = 1,
	["QtCore/QPluginLoader"] = 1,
	["QtDesigner/QFormBuilder"] = 1,
	["QtDesigner/QDesignerFormWindowManagerInterface"] = 1,
	["QtDesigner/QDesignerMemberSheetExtension"] = 1,
	["QtDesigner/QDesignerLayoutDecorationExtension"] = 1,
	["QtDesigner/QDesignerWidgetDataBaseItemInterface"] = 1,
	["QtDesigner/QDesignerContainerExtension"] = 1,
	["QtDesigner/QDesignerWidgetFactoryInterface"] = 1,
	["QtDesigner/QExtensionFactory"] = 1,
	["QtDesigner/QExtensionManager"] = 1,
	["QtDesigner/QDesignerFormEditorInterface"] = 1,
	["QtDesigner/QDesignerTaskMenuExtension"] = 1,
	["QtDesigner/QDesignerImageCollectionInterface"] = 1,
	["QtDesigner/QDesignerMetaDataBaseInterface"] = 1,
	["QtDesigner/QDesignerCustomWidgetCollectionInterface"] = 1,
	["QtDesigner/QDesignerWidgetBoxInterface"] = 1,
	["QtDesigner/QDesignerPropertyEditorInterface"] = 1,
	["QtDesigner/QDesignerDnDItemInterface"] = 1,
	["QtDesigner/QDesignerExtraInfoExtension"] = 1,
	["QtDesigner/QDesignerCustomWidgetInterface"] = 1,
	["QtDesigner/QDesignerComponents"] = 1,
	["QtDesigner/QDesignerObjectInspectorInterface"] = 1,
	["QtDesigner/QDesignerFormEditorPluginInterface"] = 1,
	["QtDesigner/QDesignerFormWindowCursorInterface"] = 1,
	["QtDesigner/QAbstractExtensionFactory"] = 1,
	["QtDesigner/QAbstractExtensionManager"] = 1,
	["QtDesigner/QDesignerMetaDataBaseItemInterface"] = 1,
	["QtDesigner/QDesignerFormWindowInterface"] = 1,
	["QtDesigner/QAbstractFormBuilder"] = 1,
	["QtDesigner/QDesignerWidgetDataBaseInterface"] = 1,
	["QtDesigner/QDesignerIconCacheInterface"] = 1,
	["QtDesigner/QDesignerPropertySheetExtension"] = 1,
	["QtDesigner/QDesignerFormWindowToolInterface"] = 1,
	["QtGui/QClipboard"] = 1,
	["QtGui/QPixmap"] = 1,
	["QtGui/QPen"] = 1,
	["QtGui/QRgb"] = 1,
	["QtGui/QMessageBox"] = 1,
	["QtGui/QRegion"] = 1,
	["QtGui/QImageReader"] = 1,
	["QtGui/QItemEditorCreator"] = 1,
	["QtGui/QTimeEdit"] = 1,
	["QtGui/QCloseEvent"] = 1,
	["QtGui/QPushButton"] = 1,
	["QtGui/QAbstractScrollArea"] = 1,
	["QtGui/QTabBar"] = 1,
	["QtGui/QSlider"] = 1,
	["QtGui/QPicture"] = 1,
	["QtGui/QRadialGradient"] = 1,
	["QtGui/QStandardItemModel"] = 1,
	["QtGui/QListWidget"] = 1,
	["QtGui/QPageSetupDialog"] = 1,
	["QtGui/QAccessibleApplication"] = 1,
	["QtGui/QHelpEvent"] = 1,
	["QtGui/QTextDocumentFragment"] = 1,
	["QtGui/QDragMoveEvent"] = 1,
	["QtGui/QImageIOHandlerFactoryInterface"] = 1,
	["QtGui/QDropEvent"] = 1,
	["QtGui/QInputContextFactoryInterface"] = 1,
	["QtGui/QStyleHintReturnMask"] = 1,
	["QtGui/QWidget"] = 1,
	["QtGui/QTextTableCell"] = 1,
	["QtGui/QPrintDialog"] = 1,
	["QtGui/QKeyEvent"] = 1,
	["QtGui/QDial"] = 1,
	["QtGui/QDrag"] = 1,
	["QtGui/QFont"] = 1,
	["QtGui/QIcon"] = 1,
	["QtGui/QItemSelection"] = 1,
	["QtGui/QMenu"] = 1,
	["QtGui/QImageWriter"] = 1,
	["QtGui/QAbstractSlider"] = 1,
	["QtGui/QtGui"] = 1,
	["QtGui/QStyleOptionToolBox"] = 1,
	["QtGui/QTableView"] = 1,
	["QtGui/QWidgetData"] = 1,
	["QtGui/QPrintEngine"] = 1,
	["QtGui/QWidgetItem"] = 1,
	["QtGui/QWidgetList"] = 1,
	["QtGui/QStyleOptionProgressBar"] = 1,
	["QtGui/QIconEnginePlugin"] = 1,
	["QtGui/QScrollBar"] = 1,
	["QtGui/QPolygon"] = 1,
	["QtGui/QAccessibleFactoryInterface"] = 1,
	["QtGui/QProgressDialog"] = 1,
	["QtGui/QStyleOptionButton"] = 1,
	["QtGui/QClipboardEvent"] = 1,
	["QtGui/QHideEvent"] = 1,
	["QtGui/QDragLeaveEvent"] = 1,
	["QtGui/QPlastiqueStyle"] = 1,
	["QtGui/QWhatsThisClickedEvent"] = 1,
	["QtGui/QBrush"] = 1,
	["QtGui/QColor"] = 1,
	["QtGui/QLineEdit"] = 1,
	["QtGui/QStyleOptionFocusRect"] = 1,
	["QtGui/QFrame"] = 1,
	["QtGui/QImage"] = 1,
	["QtGui/QPrinter"] = 1,
	["QtGui/QLabel"] = 1,
	["QtGui/QMovie"] = 1,
	["QtGui/QStyleOptionTabWidgetFrame"] = 1,
	["QtGui/QSound"] = 1,
	["QtGui/QStyle"] = 1,
	["QtGui/QMoveEvent"] = 1,
	["QtGui/QAccessibleBridge"] = 1,
	["QtGui/QStyleOptionHeader"] = 1,
	["QtGui/QFileOpenEvent"] = 1,
	["QtGui/QGradientStop"] = 1,
	["QtGui/QMenuItem"] = 1,
	["QtGui/QAbstractPageSetupDialog"] = 1,
	["QtGui/QVBoxLayout"] = 1,
	["QtGui/QItemEditorFactory"] = 1,
	["QtGui/QPainterPath"] = 1,
	["QtGui/QTextObjectInterface"] = 1,
	["QtGui/QIconEngineFactoryInterface"] = 1,
	["QtGui/QTreeView"] = 1,
	["QtGui/QStyleOptionTabBarBase"] = 1,
	["QtGui/QListView"] = 1,
	["QtGui/QGradientStops"] = 1,
	["QtGui/QRegExpValidator"] = 1,
	["QtGui/QAbstractSpinBox"] = 1,
	["QtGui/QTextFragment"] = 1,
	["QtGui/QStackedLayout"] = 1,
	["QtGui/QAccessibleEvent"] = 1,
	["QtGui/QAccessibleInterface"] = 1,
	["QtGui/QCommonStyle"] = 1,
	["QtGui/QIconEngine"] = 1,
	["QtGui/QDateEdit"] = 1,
	["QtGui/QLayoutIterator"] = 1,
	["QtGui/QPictureFormatInterface"] = 1,
	["QtGui/QTextTableFormat"] = 1,
	["QtGui/QResizeEvent"] = 1,
	["QtGui/QFontMetrics"] = 1,
	["QtGui/QGradient"] = 1,
	["QtGui/QImageIOPlugin"] = 1,
	["QtGui/QImageIOHandler"] = 1,
	["QtGui/QShortcut"] = 1,
	["QtGui/QAccessibleObject"] = 1,
	["QtGui/QTextBlockGroup"] = 1,
	["QtGui/QStyleOptionSlider"] = 1,
	["QtGui/QApplication"] = 1,
	["QtGui/QTableWidgetItem"] = 1,
	["QtGui/QInputDialog"] = 1,
	["QtGui/QPainterPathStroker"] = 1,
	["QtGui/QAccessiblePlugin"] = 1,
	["QtGui/QTextBrowser"] = 1,
	["QtGui/QStyleFactoryInterface"] = 1,
	["QtGui/QImageTextKeyLang"] = 1,
	["QtGui/QErrorMessage"] = 1,
	["QtGui/QTextFrameLayoutData"] = 1,
	["QtGui/QHoverEvent"] = 1,
	["QtGui/QX11Info"] = 1,
	["QtGui/QScrollArea"] = 1,
	["QtGui/QDirModel"] = 1,
	["QtGui/QAbstractTextDocumentLayout"] = 1,
	["QtGui/QWindowsStyle"] = 1,
	["QtGui/QStackedWidget"] = 1,
	["QtGui/QX11EmbedContainer"] = 1,
	["QtGui/QStyleOptionTitleBar"] = 1,
	["QtGui/QAbstractItemView"] = 1,
	["QtGui/QStylePainter"] = 1,
	["QtGui/QSplitter"] = 1,
	["QtGui/QStyleOptionViewItem"] = 1,
	["QtGui/QAccessibleWidget"] = 1,
	["QtGui/QVFbHeader"] = 1,
	["QtGui/QAccessible"] = 1,
	["QtGui/QTextFrameFormat"] = 1,
	["QtGui/QGridLayout"] = 1,
	["QtGui/QButtonGroup"] = 1,
	["QtGui/QFontInfo"] = 1,
	["QtGui/QProgressBar"] = 1,
	["QtGui/QLinearGradient"] = 1,
	["QtGui/QMacMime"] = 1,
	["QtGui/QContextMenuEvent"] = 1,
	["QtGui/QStyleHintReturn"] = 1,
	["QtGui/QStyleOptionQ3ListViewItem"] = 1,
	["QtGui/QActionEvent"] = 1,
	["QtGui/QActionGroup"] = 1,
	["QtGui/QDockWidget"] = 1,
	["QtGui/QWSUpdateEvent"] = 1,
	["QtGui/QStyleOptionMenuItem"] = 1,
	["QtGui/QVFbKeyData"] = 1,
	["QtGui/QWorkspace"] = 1,
	["QtGui/QAbstractItemDelegate"] = 1,
	["QtGui/QPolygonF"] = 1,
	["QtGui/QCheckBox"] = 1,
	["QtGui/QIntValidator"] = 1,
	["QtGui/QColorGroup"] = 1,
	["QtGui/QTreeWidgetItem"] = 1,
	["QtGui/QGroupBox"] = 1,
	["QtGui/QCursorShape"] = 1,
	["QtGui/QStringListModel"] = 1,
	["QtGui/QTableWidgetSelectionRange"] = 1,
	["QtGui/QSplitterHandle"] = 1,
	["QtGui/QMenuBar"] = 1,
	["QtGui/QStyleOptionDockWidget"] = 1,
	["QtGui/QWindowsXPStyle"] = 1,
	["QtGui/QPixmapCache"] = 1,
	["QtGui/QSpinBox"] = 1,
	["QtGui/QDoubleSpinBox"] = 1,
	["QtGui/QWindowStateChangeEvent"] = 1,
	["QtGui/QTextCursor"] = 1,
	["QtGui/QFontMetricsF"] = 1,
	["QtGui/QInputMethodEvent"] = 1,
	["QtGui/QShortcutEvent"] = 1,
	["QtGui/QSizeGrip"] = 1,
	["QtGui/QInputContextFactory"] = 1,
	["QtGui/QLCDNumber"] = 1,
	["QtGui/QTextEdit"] = 1,
	["QtGui/QTextItem"] = 1,
	["QtGui/QTextLine"] = 1,
	["QtGui/QTextList"] = 1,
	["QtGui/QToolButton"] = 1,
	["QtGui/QFontDatabase"] = 1,
	["QtGui/QTextFormat"] = 1,
	["QtGui/QListWidgetItem"] = 1,
	["QtGui/QAccessibleBridgeFactoryInterface"] = 1,
	["QtGui/QKeySequence"] = 1,
	["QtGui/QStyleOptionComplex"] = 1,
	["QtGui/QTableWidget"] = 1,
	["QtGui/QFontDialog"] = 1,
	["QtGui/QTextInlineObject"] = 1,
	["QtGui/QStyleOptionFrame"] = 1,
	["QtGui/QComboBox"] = 1,
	["QtGui/QTextListFormat"] = 1,
	["QtGui/QHBoxLayout"] = 1,
	["QtGui/QColormap"] = 1,
	["QtGui/QInputContextPlugin"] = 1,
	["QtGui/QDragEnterEvent"] = 1,
	["QtGui/QStyleOptionQ3ListView"] = 1,
	["QtGui/QDragResponseEvent"] = 1,
	["QtGui/QValidator"] = 1,
	["QtGui/QStyleOptionToolButton"] = 1,
	["QtGui/QItemDelegate"] = 1,
	["QtGui/QStyleOptionQ3DockWindow"] = 1,
	["QtGui/QTextDocument"] = 1,
	["QtGui/QWMatrix"] = 1,
	["QtGui/QTextLayout"] = 1,
	["QtGui/QTextLength"] = 1,
	["QtGui/QTreeWidget"] = 1,
	["QtGui/QRadioButton"] = 1,
	["QtGui/QSplashScreen"] = 1,
	["QtGui/QToolBarChangeEvent"] = 1,
	["QtGui/QTextCharFormat"] = 1,
	["QtGui/QToolBar"] = 1,
	["QtGui/QToolBox"] = 1,
	["QtGui/QToolTip"] = 1,
	["QtGui/QX11EmbedWidget"] = 1,
	["QtGui/QDesktopWidget"] = 1,
	["QtGui/QDoubleValidator"] = 1,
	["QtGui/QShowEvent"] = 1,
	["QtGui/QTextObject"] = 1,
	["QtGui/QConicalGradient"] = 1,
	["QtGui/QTextOption"] = 1,
	["QtGui/QDateTimeEdit"] = 1,
	["QtGui/QWidgetMapper"] = 1,
	["QtGui/QWindowsMime"] = 1,
	["QtGui/QStyleOption"] = 1,
	["QtGui/QLayoutItem"] = 1,
	["QtGui/QTextBlock"] = 1,
	["QtGui/QTextImageFormat"] = 1,
	["QtGui/QStylePlugin"] = 1,
	["QtGui/QTextFrame"] = 1,
	["QtGui/QPaintDevice"] = 1,
	["QtGui/QSizePolicy"] = 1,
	["QtGui/QAccessibleBridgePlugin"] = 1,
	["QtGui/QTextTable"] = 1,
	["QtGui/QFocusEvent"] = 1,
	["QtGui/QAction"] = 1,
	["QtGui/QFocusFrame"] = 1,
	["QtGui/QTextBlockFormat"] = 1,
	["QtGui/QHeaderView"] = 1,
	["QtGui/QPaintEngine"] = 1,
	["QtGui/QMainWindow"] = 1,
	["QtGui/QBitmap"] = 1,
	["QtGui/QAbstractUndoItem"] = 1,
	["QtGui/QSpacerItem"] = 1,
	["QtGui/QFileIconProvider"] = 1,
	["QtGui/QColorDialog"] = 1,
	["QtGui/QPictureFormatPlugin"] = 1,
	["QtGui/QDialog"] = 1,
	["QtGui/QCDEStyle"] = 1,
	["QtGui/QCursor"] = 1,
	["QtGui/QTabWidget"] = 1,
	["QtGui/QItemSelectionModel"] = 1,
	["QtGui/QFileDialog"] = 1,
	["QtGui/QInputEvent"] = 1,
	["QtGui/QItemSelectionRange"] = 1,
	["QtGui/QProxyModel"] = 1,
	["QtGui/QRubberBand"] = 1,
	["QtGui/QItemEditorCreatorBase"] = 1,
	["QtGui/QMotifStyle"] = 1,
	["QtGui/QPainterPathPrivate"] = 1,
	["QtGui/QStatusTipEvent"] = 1,
	["QtGui/QPaintEngineState"] = 1,
	["QtGui/QAbstractButton"] = 1,
	["QtGui/QPictureIO"] = 1,
	["QtGui/QWheelEvent"] = 1,
	["QtGui/QAbstractPrintDialog"] = 1,
	["QtGui/QBrushData"] = 1,
	["QtGui/QInputContext"] = 1,
	["QtGui/QMouseEvent"] = 1,
	["QtGui/QStyleOptionRubberBand"] = 1,
	["QtGui/QBoxLayout"] = 1,
	["QtGui/QLayout"] = 1,
	["QtGui/QPainter"] = 1,
	["QtGui/QPalette"] = 1,
	["QtGui/QMatrix"] = 1,
	["QtGui/QIconSet"] = 1,
	["QtGui/QStyleOptionComboBox"] = 1,
	["QtGui/QSessionManager"] = 1,
	["QtGui/QStyleOptionSpinBox"] = 1,
	["QtGui/QTabletEvent"] = 1,
	["QtGui/QStyleOptionTab"] = 1,
	["QtGui/QStatusBar"] = 1,
	["QtGui/QWhatsThis"] = 1,
	["QtGui/QPaintEvent"] = 1,
	["QtGui/QStyleFactory"] = 1,
	["QtGui/QIconDragEvent"] = 1,
	["QtNetwork/QFtp"] = 1,
	["QtNetwork/QTcpServer"] = 1,
	["QtNetwork/QTcpSocket"] = 1,
	["QtNetwork/QHttp"] = 1,
	["QtNetwork/QAbstractSocket"] = 1,
	["QtNetwork/QIPv6Address"] = 1,
	["QtNetwork/QUdpSocket"] = 1,
	["QtNetwork/QHttpHeader"] = 1,
	["QtNetwork/QtNetwork"] = 1,
	["QtNetwork/QHttpResponseHeader"] = 1,
	["QtNetwork/QHttpRequestHeader"] = 1,
	["QtNetwork/QHostInfo"] = 1,
	["QtNetwork/Q_IPV6ADDR"] = 1,
	["QtNetwork/QUrlInfo"] = 1,
	["QtNetwork/QHostAddress"] = 1,
	["QtOpenGL/QGLContext"] = 1,
	["QtOpenGL/QGLFormat"] = 1,
	["QtOpenGL/QGLWidget"] = 1,
	["QtOpenGL/QGLColormap"] = 1,
	["QtOpenGL/QtOpenGL"] = 1,
	["QtSql/QSqlRelationalDelegate"] = 1,
	["QtSql/QtSql"] = 1,
	["QtSql/QPSQLResult"] = 1,
	["QtSql/QSqlDriver"] = 1,
	["QtSql/QSqlDriverFactoryInterface"] = 1,
	["QtSql/QSqlTableModel"] = 1,
	["QtSql/QIBaseDriver"] = 1,
	["QtSql/QSqlRelation"] = 1,
	["QtSql/QSqlRecord"] = 1,
	["QtSql/QSqlResult"] = 1,
	["QtSql/QSqlDriverPlugin"] = 1,
	["QtSql/QSqlDatabase"] = 1,
	["QtSql/QIBaseResult"] = 1,
	["QtSql/QSQLiteDriver"] = 1,
	["QtSql/QSqlDriverCreatorBase"] = 1,
	["QtSql/QSQLite2Driver"] = 1,
	["QtSql/QSqlError"] = 1,
	["QtSql/QSqlField"] = 1,
	["QtSql/QSqlIndex"] = 1,
	["QtSql/QSqlQuery"] = 1,
	["QtSql/QODBCDriver"] = 1,
	["QtSql/QSQLiteResult"] = 1,
	["QtSql/QSQLite2Result"] = 1,
	["QtSql/QSqlRelationalTableModel"] = 1,
	["QtSql/QMYSQLDriver"] = 1,
	["QtSql/QODBCResult"] = 1,
	["QtSql/QSqlDriverCreator"] = 1,
	["QtSql/QSqlQueryModel"] = 1,
	["QtSql/QPSQLDriver"] = 1,
	["QtSql/QMYSQLResult"] = 1,
	["QtXml/QDomProcessingInstruction"] = 1,
	["QtXml/QXmlContentHandler"] = 1,
	["QtXml/QXmlParseException"] = 1,
	["QtXml/QXmlLexicalHandler"] = 1,
	["QtXml/QtXml"] = 1,
	["QtXml/QDomNodeList"] = 1,
	["QtXml/QDomElement"] = 1,
	["QtXml/QDomDocument"] = 1,
	["QtXml/QDomDocumentType"] = 1,
	["QtXml/QDomAttr"] = 1,
	["QtXml/QDomNode"] = 1,
	["QtXml/QDomText"] = 1,
	["QtXml/QDomEntity"] = 1,
	["QtXml/QDomNotation"] = 1,
	["QtXml/QXmlDefaultHandler"] = 1,
	["QtXml/QDomDocumentFragment"] = 1,
	["QtXml/QXmlDeclHandler"] = 1,
	["QtXml/QXmlAttributes"] = 1,
	["QtXml/QXmlEntityResolver"] = 1,
	["QtXml/QDomImplementation"] = 1,
	["QtXml/QXmlInputSource"] = 1,
	["QtXml/QXmlLocator"] = 1,
	["QtXml/QXmlReader"] = 1,
	["QtXml/QDomNamedNodeMap"] = 1,
	["QtXml/QXmlDTDHandler"] = 1,
	["QtXml/QXmlErrorHandler"] = 1,
	["QtXml/QDomCharacterData"] = 1,
	["QtXml/QDomEntityReference"] = 1,
	["QtXml/QXmlNamespaceSupport"] = 1,
	["QtXml/QXmlSimpleReader"] = 1,
	["QtXml/QDomCDATASection"] = 1,
	["QtXml/QDomComment"] = 1,
	["Qt3Support/Q3Frame"] = 1,
	["Qt3Support/Q3HBox"] = 1,
	["Qt3Support/Q3VBox"] = 1,
	["Qt3Support/Q3ScrollView"] = 1,
	["Qt3Support/Q3ListView"] = 1,
	["Qt3Support/Q3ListViewItem"] = 1,
	["Qt3Support/Q3CheckListItem"] = 1,
	["Qt3Support/Q3ListViewItemIterator"] = 1,

	["Qt3Support/Q3Canvas"] = 1,
	["Qt3Support/Q3CanvasEllipse"] = 1,
	["Qt3Support/Q3CanvasItem"] = 1,
	["Qt3Support/Q3CanvasItemList"] = 1,
	["Qt3Support/Q3CanvasLine"] = 1,
	["Qt3Support/Q3CanvasPixmap"] = 1,
	["Qt3Support/Q3CanvasPixmapArray"] = 1,
	["Qt3Support/Q3CanvasPolygon"] = 1,
	["Qt3Support/Q3CanvasPolygonalItem"] = 1,
	["Qt3Support/Q3CanvasRectangle"] = 1,
	["Qt3Support/Q3CanvasSpline"] = 1,
	["Qt3Support/Q3CanvasSprite"] = 1,
	["Qt3Support/Q3CanvasText"] = 1,
	["Qt3Support/Q3CanvasView"] = 1,
}

class_list = {
	"Q3Picture",
	"QDesignerWidgetDataBaseInterface",
	"QItemDelegate",
	"QRadialGradient",
	"QTableWidget",
	"QAbstractButton",
	"QDesignerWidgetDataBaseItemInterface",
	"QItemEditorCreatorBase",
	"QRadioButton",
	"QTableWidgetItem",
	"QAbstractEventDispatcher",
	"QDesignerWidgetFactoryInterface",
	"QItemEditorFactory",
	"QReadLocker",
	"QTableWidgetSelectionRange",
	"QAbstractExtensionFactory",
	"QDesktopWidget",
	"QItemSelection",
	"QReadWriteLock",
	"QTabWidget",
	"QAbstractExtensionManager",
	"QDial",
	"QItemSelectionModel",
	"QRect",
	"QTcpServer",
	"QAbstractFormBuilder",
	"QDialog",
	"QItemSelectionRange",
	"QRectF",
	"QTcpSocket",
	"QAbstractItemDelegate",
	"QDir",
	"QKbdDriverFactory",
	"QRegExp",
	"QTemporaryFile",
	"QAbstractItemModel",
	"QDirectPainter",
	"QKbdDriverPlugin",
	"QRegExpValidator",
	"QTextBlock",
	"QAbstractItemView",
	"QDirModel",
	"QKeyEvent",
	"QRegion",
	"QTextBlockFormat",
	"QAbstractListModel",
	"QDockWidget",
	"QKeySequence",
	"QResizeEvent",
	"QTextBlockGroup",
	"QAbstractPageSetupDialog",
	"QDomAttr",
	"QLabel",
	"QRubberBand",
	"QTextBrowser",
	"QAbstractPrintDialog",
	"QDomCDATASection",
	"QLatin1Char",
	"QScreen",
	"QTextCharFormat",
	"QAbstractScrollArea",
	"QDomCharacterData",
	"QLatin1String",
	"QScrollArea",
	"QTextCodec",
	"QAbstractSlider",
	"QDomComment",
	"QLayout",
	"QScrollBar",
	"QTextCodecPlugin",
	"QAbstractSocket",
	"QDomDocument",
	"QLayoutItem",
	"QSemaphore",
	"QTextCursor",
	"QAbstractSpinBox",
	"QDomDocumentFragment",
	"QLCDNumber",
	"QSessionManager",
	"QTextDecoder",
	"QAbstractTableModel",
	"QDomDocumentType",
	"QLibrary",
	"QSet",
	"QTextDocument",
	"QAbstractTextDocumentLayout",
	"QDomElement",
	"QLibraryInfo",
	"QSetIterator",
	"QTextDocumentFragment",
	"QAccessible",
	"QDomEntity",
	"QLine",
	"QSettings",
	"QTextEdit",
	"QAccessibleBridge",
	"QDomEntityReference",
	"QLinearGradient",
	"QSharedData",
	"QTextEncoder",
	"QAccessibleBridgePlugin",
	"QDomImplementation",
	"QLineEdit",
	"QSharedDataPointer",
	"QTextFormat",
	"QAccessibleEvent",
	"QDomNamedNodeMap",
	"QLineF",
	"QShortcut",
	"QTextFragment",
	"QAccessibleInterface",
	"QDomNode",
	"QLinkedList",
	"QShortcutEvent",
	"QTextFrame",
	"QAccessibleObject",
	"QDomNodeList",
	"QLinkedListIterator",
	"QShowEvent",
	"QTextFrameFormat",
	"QAccessiblePlugin",
	"QDomNotation",
	"QList",
	"QSignalMapper",
	"QTextImageFormat",
	"QAccessibleWidget",
	"QDomProcessingInstruction",
	"QListIterator",
	"QSize",
	"QTextInlineObject",
	"QAction",
	"QDomText",
	"QListView",
	"QSizeF",
	"QTextLayout",
	"QActionEvent",
	"QDoubleSpinBox",
	"QListWidget",
	"QSizeGrip",
	"QTextLength",
	"QActionGroup",
	"QDoubleValidator",
	"QListWidgetItem",
	"QSizePolicy",
	"QTextLine",
	"QApplication",
	"QDrag",
	"QLocale",
	"QSlider",
	"QTextList",
	"QAxAggregated",
	"QDragEnterEvent",
	"QMacMime",
	"QSocketNotifier",
	"QTextListFormat",
	"QAxBase",
	"QDragLeaveEvent",
	"QMacStyle",
	"QSound",
	"QTextObject",
	"QAxBindable",
	"QDragMoveEvent",
	"QMainWindow",
	"QSpacerItem",
	"QTextOption",
	"QAxFactory",
	"QDropEvent",
	"QMap",
	"QSpinBox",
	"QTextStream",
	"QAxObject",
	"QErrorMessage",
	"QMapIterator",
	"QSplashScreen",
	"QTextTable",
	"QAxScript",
	"QEvent",
	"QMatrix",
	"QSplitter",
	"QTextTableCell",
	"QAxScriptEngine",
	"QEventLoop",
	"QMenu",
	"QSplitterHandle",
	"QTextTableFormat",
	"QAxScriptManager",
	"QExtensionFactory",
	"QMenuBar",
	"QSqlDatabase",
	"QThread",
	"QAxWidget",
	"QExtensionManager",
	"QMessageBox",
	"QSqlDriver",
	"QThreadStorage",
	"QBasicTimer",
	"QFile",
	"QMetaClassInfo",
	"QSqlDriverCreator",
	"QTime",
	"QBitArray",
	"QFileDialog",
	"QMetaEnum",
	"QSqlDriverCreatorBase",
	"QTimeEdit",
	"QBitmap",
	"QFileIconProvider",
	"QMetaMethod",
	"QSqlDriverPlugin",
	"QTimer",
	"QBoxLayout",
	"QFileInfo",
	"QMetaObject",
	"QSqlError",
	"QTimerEvent",
	"QBrush",
	"QFileOpenEvent",
	"QMetaProperty",
	"QSqlField",
	"QToolBar",
	"QBuffer",
	"QFlag",
	"QMetaType",
	"QSqlIndex",
	"QToolBox",
	"QButtonGroup",
	"QFlags",
	"QMimeData",
	"QSqlQuery",
	"QToolButton",
	"QByteArray",
	"QFocusEvent",
	"QModelIndex",
	"QSqlQueryModel",
	"QToolTip",
	"QByteArrayMatcher",
	"QFocusFrame",
	"QMotifStyle",
	"QSqlRecord",
	"QTranslator",
	"QCache",
	"QFont",
	"QMouseDriverFactory",
	"QSqlRelation",
	"QTreeView",
	"QCDEStyle",
	"QFontDatabase",
	"QMouseDriverPlugin",
	"QSqlRelationalDelegate",
	"QTreeWidget",
	"QChar",
	"QFontDialog",
	"QMouseEvent",
	"QSqlRelationalTableModel",
	"QTreeWidgetItem",
	"QCheckBox",
	"QFontInfo",
	"QMoveEvent",
	"QSqlResult",
	"QUdpSocket",
	"QChildEvent",
	"QFontMetrics",
	"QMovie",
	"QSqlTableModel",
	"QUrl",
	"QClipboard",
	"QFontMetricsF",
	"QMultiHash",
	"QStack",
	"QUrlInfo",
	"QCloseEvent",
	"QFormBuilder",
	"QMultiMap",
	"QStackedLayout",
	"QUuid",
	"QColor",
	"QFrame",
	"QMutableHashIterator",
	"QStackedWidget",
	"QValidator",
	"QColorDialog",
	"QFtp",
	"QMutableLinkedListIterator",
	"QStandardItemModel",
	"QVariant",
	"QColormap",
	"QGfxDriverFactory",
	"QMutableListIterator",
	"QStatusBar",
	"QVarLengthArray",
	"QComboBox",
	"QGfxDriverPlugin",
	"QMutableMapIterator",
	"QStatusTipEvent",
	"QVBoxLayout",
	"QCommonStyle",
	"QGLColormap",
	"QMutableVectorIterator",
	"QString",
	"QVector",
	"QConicalGradient",
	"QGLContext",
	"QMutex",
	"QStringList",
	"QVectorIterator",
	"QContextMenuEvent",
	"QGLFormat",
	"QMutexLocker",
	"QStringListModel",
	"QWaitCondition",
	"QCopChannel",
	"QGLWidget",
	"QObject",
	"QStringMatcher",
	"QWhatsThis",
	"QCoreApplication",
	"QGradient",
	"QObjectCleanupHandler",
	"QStyle",
	"QWhatsThisClickedEvent",
	"QCursor",
	"QGridLayout",
	"QPageSetupDialog",
	"QStyleFactory",
	"QWheelEvent",
	"QDataStream",
	"QGroupBox",
	"QPaintDevice",
	"QStyleHintReturn",
	"QWidget",
	"QDate",
	"QHash",
	"QPaintEngine",
	"QStyleHintReturnMask",
	"QWidgetItem",
	"QDateEdit",
	"QHashIterator",
	"QPainter",
	"QStyleOption",
	"QWindowsMime",
	"QDateTime",
	"QHBoxLayout",
	"QPainterPath",
	"QStyleOptionButton",
	"QWindowsStyle",
	"QDateTimeEdit",
	"QHeaderView",
	"QPaintEvent",
	"QStyleOptionComboBox",
	"QWindowStateChangeEvent",
	"QDecoration",
	"QHelpEvent",
	"QPair",
	"QStyleOptionComplex",
	"QWindowsXPStyle",
	"QDecorationFactory",
	"QHideEvent",
	"QPalette",
	"QStyleOptionDockWidget",
	"QWorkspace",
	"QDecorationPlugin",
	"QHostAddress",
	"QPen",
	"QStyleOptionFocusRect",
	"QWriteLocker",
	"QDesignerContainerExtension",
	"QHostInfo",
	"QPersistentModelIndex",
	"QStyleOptionFrame",
	"QWSInputMethod",
	"QDesignerCustomWidgetCollectionInterface",
	"QHoverEvent",
	"QPicture",
	"QStyleOptionHeader",
	"QWSKeyboardHandler",
	"QDesignerCustomWidgetInterface",
	"QHttp",
	"QPictureFormatPlugin",
	"QStyleOptionMenuItem",
	"QWSMouseHandler",
	"QDesignerDnDItemInterface",
	"QHttpHeader",
	"QPictureIO",
	"QStyleOptionProgressBar",
	"QWSServer",
	"QDesignerExtraInfoExtension",
	"QHttpRequestHeader",
	"QPixmap",
	"QStyleOptionQ3DockWindow",
	"QWSWindow",
	"QDesignerFormEditorInterface",
	"QHttpResponseHeader",
	"QPixmapCache",
	"QStyleOptionQ3ListView",
	"QX11EmbedContainer",
	"QDesignerFormEditorPluginInterface",
	"QIcon",
	"QPlastiqueStyle",
	"QStyleOptionQ3ListViewItem",
	"QX11EmbedWidget",
	"QDesignerFormWindowCursorInterface",
	"QIconDragEvent",
	"QPluginLoader",
	"QStyleOptionRubberBand",
	"QX11Info",
	"QDesignerFormWindowInterface",
	"QIconEngine",
	"QPoint",
	"QStyleOptionSlider",
	"QXmlAttributes",
	"QDesignerFormWindowManagerInterface",
	"QIconEnginePlugin",
	"QPointer",
	"QStyleOptionSpinBox",
	"QXmlContentHandler",
	"QDesignerFormWindowToolInterface",
	"QImage",
	"QPointF",
	"QStyleOptionTab",
	"QXmlDeclHandler",
	"QDesignerIconCacheInterface",
	"QImageIOHandler",
	"QPolygon",
	"QStyleOptionTabWidgetFrame",
	"QXmlDefaultHandler",
	"QDesignerImageCollectionInterface",
	"QImageIOPlugin",
	"QPolygonF",
	"QStyleOptionTitleBar",
	"QXmlDTDHandler",
	"QDesignerLayoutDecorationExtension",
	"QImageReader",
	"QPrintDialog",
	"QStyleOptionToolBox",
	"QXmlEntityResolver",
	"QDesignerMemberSheetExtension",
	"QImageWriter",
	"QPrintEngine",
	"QStyleOptionToolButton",
	"QXmlErrorHandler",
	"QDesignerMetaDataBaseInterface",
	"QInputContext",
	"QPrinter",
	"QStyleOptionViewItem",
	"QXmlInputSource",
	"QDesignerMetaDataBaseItemInterface",
	"QInputContextPlugin",
	"QProcess",
	"QStylePainter",
	"QXmlLexicalHandler",
	"QDesignerObjectInspectorInterface",
	"QInputDialog",
	"QProgressBar",
	"QStylePlugin",
	"QXmlLocator",
	"QDesignerPropertyEditorInterface",
	"QInputEvent",
	"QProgressDialog",
	"QSysInfo",
	"QXmlNamespaceSupport",
	"QDesignerPropertySheetExtension",
	"QInputMethodEvent",
	"QProxyModel",
	"QTabBar",
	"QXmlParseException",
	"QDesignerTaskMenuExtension",
	"QIntValidator",
	"QPushButton",
	"QTabletEvent",
	"QXmlReader",
	"QDesignerWidgetBoxInterface",
	"QIODevice",
	"QQueue",
	"QTableView",
	"QXmlSimpleReader",
	"Q3Frame",
	"Q3HBox",
	"Q3VBox",
	"Q3ScrollView",
	"Q3ListView",
	"Q3ListViewItem",
	"Q3CheckListItem",
	"Q3ListViewItemIterator",

	"Q3Canvas",
	"Q3CanvasEllipse",
	"Q3CanvasItem",
	"Q3CanvasItemList",
	"Q3CanvasLine",
	"Q3CanvasPixmap",
	"Q3CanvasPixmapArray",
	"Q3CanvasPolygon",
	"Q3CanvasPolygonalItem",
	"Q3CanvasRectangle",
	"Q3CanvasSpline",
	"Q3CanvasSprite",
	"Q3CanvasText",
	"Q3CanvasView",
}
